apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "falcon-kac.fullname" . }}-rq
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "falcon-kac.labels" . | nindent 4 }}
spec:
  hard:
    pods: 2
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - system-cluster-critical
